# Generated by Django 6.0.7 on 2026-08-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_number', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(max_length=150)),
                ('child_number', models.CharField(max_length=50, unique=True)),
                ('participant_case_number', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, default='', max_length=150)),
                ('sponsorship_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Graduated', 'Graduated'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('narrative_date', models.DateField(blank=True, null=True)),
                ('photo_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='beneficiary_docs/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaries.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='You', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='beneficiaries.beneficiary')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.EmailField(blank=True, default='', max_length=254)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_logs', to='beneficiaries.beneficiary')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
