# Generated by Django 6.0.7 on 2026-08-05 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['-child_number']},
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='child_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='community_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='sponsorship_status',
            field=models.CharField(choices=[('Sponsored', 'Sponsored'), ('Pre-Sponsored', 'Pre-Sponsored'), ('Enrolled', 'Enrolled'), ('Reinstateable', 'Reinstateable'), ('Available', 'Available'), ('Reserved', 'Reserved'), ('Check Materials', 'Check Materials'), ('Unavailable', 'Unavailable')], default='Sponsored', max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='village',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['last_name'], name='beneficiari_last_na_1721e5_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['child_number'], name='beneficiari_child_n_a4dff3_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['short_name'], name='beneficiari_short_n_fc351a_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['village'], name='beneficiari_village_3ceb07_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['community_number'], name='beneficiari_communi_a420d5_idx'),
        ),
    ]
