# Generated by Django 6.0.8 on 2026-08-25 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_options_beneficiary_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('id_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='sponsorship_status',
            field=models.CharField(choices=[('Sponsored', 'Sponsored'), ('Pre-Sponsored', 'Pre-Sponsored'), ('Enrolled', 'Enrolled'), ('Reinstateable', 'Reinstateable'), ('Available', 'Available'), ('Reserved', 'Reserved'), ('Check Materials', 'Check Materials'), ('Unavailable', 'Unavailable')], db_index=True, default='Sponsored', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportlog',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['sponsorship_status'], name='beneficiari_sponsor_2a8ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['created_by'], name='beneficiari_created_081c04_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['-child_number'], name='beneficiari_child_n_ec8d43_idx'),
        ),
        migrations.AddIndex(
            model_name='supportlog',
            index=models.Index(fields=['status'], name='beneficiari_status_bf0317_idx'),
        ),
        migrations.AddIndex(
            model_name='supportlog',
            index=models.Index(fields=['date'], name='beneficiari_date_f84aab_idx'),
        ),
        migrations.AddIndex(
            model_name='supportlog',
            index=models.Index(fields=['beneficiary', 'status'], name='beneficiari_benefic_7193f2_idx'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='beneficiaries.beneficiary'),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('beneficiary', 'relationship')},
        ),
    ]
