# Generated by Django 6.0.7 on 2026-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_role_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_auth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
