# Generated by Django 6.0.8 on 2026-08-27 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_activity_user_last_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_USER', 'Create User'), ('DELETE_USER', 'Delete User'), ('UPDATE_USER_STATUS', 'Update User Status'), ('RESET_PASSWORD', 'Reset Password'), ('PASSWORD_CHANGE', 'Password Change'), ('ADD_BENEFICIARY', 'Add Beneficiary'), ('EDIT_BENEFICIARY', 'Edit Beneficiary'), ('DELETE_BENEFICIARY', 'Delete Beneficiary'), ('ADD_DISBURSEMENT', 'Add Disbursement'), ('EDIT_DISBURSEMENT', 'Edit Disbursement'), ('DELETE_DISBURSEMENT', 'Delete Disbursement'), ('BULK_IMPORT_BENEFICIARIES', 'Bulk Import Beneficiaries'), ('BULK_IMPORT_DISBURSEMENTS', 'Bulk Import Disbursements'), ('IMPORT_GUARDIANS', 'Import Guardians')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
