# Generated by Django 6.0.8 on 2026-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_picture_chatmessage_publickey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='encrypted_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
