# Generated by Django 6.0.8 on 2026-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_chatmessage_encrypted_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('supervisor', 'Supervisor'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
