# Generated by Django 6.0.8 on 2026-08-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('bursaries', 'Bursaries'), ('scholarships', 'Scholarship'), ('child-friendly-desks', 'Provision of Child Friendly Desks'), ('school-infrastructure', 'Improvement of School Infrastructure'), ('asali-tamu', 'Asali Tamu Initiative'), ('sahiwal-heifers', 'Provision of Sahiwal Heifers'), ('galla-goats', 'Provision of Galla Goats'), ('kienyeji-chicks', 'Provision of Improved Kienyeji Chicks'), ('vsla-tents-chairs', 'Provision of Tents & Chairs to VSLA Groups'), ('moilo-water-project', 'Development of Moilo Water Project'), ('olkina-water-project', 'Development of Olkina Water Project'), ('lenkisim-water-project', 'Development of Lenkisim Water Project'), ('nataana-water-project', 'Rehabilitation of Nataana Water Project'), ('water-tanks-gutters', 'Provision of Water Tanks & Installation of Gutters'), ('drought-tolerant-seeds', 'Provision of Drought Tolerant Seeds'), ('aflatoun-4k-clubs', 'Establishment Aflatoun 4K Clubs'), ('school-feeding', 'School Feeding Programs')], max_length=50)),
                ('zone', models.CharField(blank=True, default='', max_length=150)),
                ('case_number', models.CharField(blank=True, default='', max_length=150)),
                ('admission_number', models.CharField(blank=True, default='', max_length=150)),
                ('beneficiary_name', models.CharField(blank=True, default='', max_length=255)),
                ('school', models.CharField(blank=True, default='', max_length=255)),
                ('grade', models.CharField(blank=True, default='', max_length=100)),
                ('performance', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=150)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_zone_dbc0bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_case_nu_e6dbd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_admissi_cd666f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_benefic_50eb8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_school_2d8b0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_account_bed83c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_status_d84dc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='bursary',
            name='disbursemen_date_31bfee_idx',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bursary',
            name='created_by',
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['program'], name='disbursemen_program_ed0b73_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['zone'], name='disbursemen_zone_39d68f_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['case_number'], name='disbursemen_case_nu_39eaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['admission_number'], name='disbursemen_admissi_40156e_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['beneficiary_name'], name='disbursemen_benefic_e65b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['school'], name='disbursemen_school_08b1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['account_number'], name='disbursemen_account_97f01c_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['status'], name='disbursemen_status_eececd_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['date'], name='disbursemen_date_796747_idx'),
        ),
        migrations.DeleteModel(
            name='Bursary',
        ),
    ]
