# Generated by Django 6.0.8 on 2026-09-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0002_disbursement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, default='', max_length=150)),
                ('case_number', models.CharField(blank=True, default='', max_length=150)),
                ('admission_number', models.CharField(blank=True, default='', max_length=150)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('school', models.CharField(blank=True, default='', max_length=255)),
                ('grade', models.CharField(blank=True, default='', max_length=100)),
                ('performance', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=150)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_program_ed0b73_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_zone_39d68f_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_case_nu_39eaf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_admissi_40156e_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_benefic_e65b9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_school_08b1a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_account_97f01c_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_status_eececd_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='disbursemen_date_796747_idx',
        ),
        migrations.AddField(
            model_name='bursary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bursaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='created_by',
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['zone'], name='disbursemen_zone_dbc0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['case_number'], name='disbursemen_case_nu_e6dbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['admission_number'], name='disbursemen_admissi_cd666f_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['beneficiary_name'], name='disbursemen_benefic_50eb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['school'], name='disbursemen_school_2d8b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['account_number'], name='disbursemen_account_bed83c_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['status'], name='disbursemen_status_d84dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='bursary',
            index=models.Index(fields=['date'], name='disbursemen_date_31bfee_idx'),
        ),
        migrations.DeleteModel(
            name='Disbursement',
        ),
    ]
